exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: Slate

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/RodneyMcCoy/RodneyMcCoy"
  
title: A
description: B
